server:
  port: 8082

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sr-test-mysql-master-1.gz.cvte.cn:3306/seewo_live_server?characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: seewo
    password: seewo@cvte
    hikari:
      minimum-idle: 20
      maximum-pool-size: 20
      idle-timeout: 100000
      max-lifetime: 270000
      connection-timeout: 30000
  redis:
    host: sr-test-redis-master-1.gz.cvte.cn
    port: 6379
    database: 0
    time: 60000
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8


#Redisson配置
singleServerConfig:
  address: "redis://redis-seewo-test-public-6624-master.paas.cvtecs.com:6624"
  password: "mOLPkVDihC"
  clientName: null
  database: 12 #选择使用哪个数据库0~15
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 60000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  dnsMonitoringInterval: 5000
  #dnsMonitoring: false

threads: 0
nettyThreads: 0
codec:
  class: "org.redisson.codec.MarshallingCodec"
transportMode: "NIO"